tick_interval_secs = 1
storage_path = "./temp/events.toml"

[oracle]
addresses = ["http://geth:26657"]

[blockchain]
addresses = ["http://kms-validator:9090"]
contract = "wasm1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqr5j2ht"

[blockchain.signkey]
# It should be either mnemonic or bip32
mnemonic = "bachelor similar spirit copper rely carbon web hobby conduct wrap conduct wire shine parrot erosion divert crucial balance lock reason price ignore educate open"
bip32 = "xprv9s21ZrQH143K3FQVQn1Z6"

[blockchain.fee]
denom = "ucosm"
amount = 3000000

[core]
addresses = ["http://kms-core:50051"]

[core.timeout_config]
channel_timeout = 60

[core.timeout_config.crs]
initial_wait_time = 60
retry_interval = 60
max_poll_count = 120

[core.timeout_config.keygen]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.preproc]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.decryption]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[core.timeout_config.reencryption]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[core.timeout_config.zkp]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[core.timeout_config.insecure_keygen]
initial_wait_time = 1
retry_interval = 3
max_poll_count = 24


[tracing]
service_name = "kms-asc-connector"
endpoint = "http://connector:4317"

[store]
url = "http://gateway-store:8088"
